#!/usr/bin/env Rscript

###############################################################################
# Prepare flanking regions around RetroInspector insertion breakpoints
#
# PURPOSE
# -------
# Generate left and right genomic windows around non-reference TE insertion
# breakpoints for regional methylation analysis.
#
# In the paper, the primary analysis used 500-bp windows immediately upstream
# and downstream of each RetroInspector-defined insertion breakpoint.
#
# The resulting BED files can be supplied directly to
# `02_regional_methylation.sh`.
#
# USAGE
# -----
#   Rscript prepare_flanking_regions.R \
#       internal_TE_input.tsv \
#       output_directory \
#       500 \
#       one_based
#
# INPUT
# -----
# A four-column tab-separated file WITHOUT a header:
#
#   TE_ID    chromosome    insertion_position    insertion_sequence
#
# This is the format generated by `prepare_internal_TE_input.R`.
#
# ARGUMENTS
# ---------
# 1. input.tsv
# 2. output_directory
# 3. window_size
#       Example: 500
# 4. coordinate_mode
#       "bed0"      : insertion_position is already a 0-based BED breakpoint
#       "one_based" : insertion_position is 1-based and will be converted to
#                     a 0-based breakpoint before BED windows are generated
#
# OUTPUTS
# -------
# <output_directory>/left.bed
# <output_directory>/right.bed
# <output_directory>/flanking_regions_map.tsv
#
# BED coordinates are 0-based, half-open.
#
# For a breakpoint p expressed in BED coordinates:
#
#   LEFT  = [max(0, p-window), p)
#   RIGHT = [p, p+window)
#
# REQUIREMENTS
# ------------
# R
# dplyr
# readr
###############################################################################

suppressPackageStartupMessages({
  library(dplyr)
  library(readr)
})

args <- commandArgs(trailingOnly = TRUE)

if (length(args) != 4) {
  stop(
    paste0(
      "Usage: Rscript prepare_flanking_regions.R ",
      "<input.tsv> <output_directory> <window_size> <bed0|one_based>"
    )
  )
}

input_path <- args[1]
output_dir <- args[2]
window_size <- suppressWarnings(as.integer(args[3]))
coordinate_mode <- args[4]

if (!file.exists(input_path)) {
  stop("Input file does not exist: ", input_path)
}

if (is.na(window_size) || window_size <= 0) {
  stop("window_size must be a positive integer.")
}

if (!coordinate_mode %in% c("bed0", "one_based")) {
  stop("coordinate_mode must be either 'bed0' or 'one_based'.")
}

insertions <- read.delim(
  input_path,
  header = FALSE,
  sep = "\t",
  stringsAsFactors = FALSE,
  check.names = FALSE
)

if (ncol(insertions) < 3) {
  stop("Input must contain at least TE_ID, chromosome, and insertion_position.")
}

colnames(insertions)[1:3] <- c(
  "TE_ID",
  "chromosome",
  "insertion_position"
)

insertions$insertion_position <- suppressWarnings(
  as.numeric(insertions$insertion_position)
)

if (anyNA(insertions$insertion_position)) {
  stop("At least one insertion position is not numeric.")
}

# Convert the insertion breakpoint to a BED-compatible 0-based coordinate.
if (coordinate_mode == "one_based") {
  insertions <- insertions %>%
    mutate(breakpoint_bed0 = insertion_position - 1)
} else {
  insertions <- insertions %>%
    mutate(breakpoint_bed0 = insertion_position)
}

if (any(insertions$breakpoint_bed0 < 0)) {
  stop("At least one converted breakpoint is negative.")
}

regions <- insertions %>%
  mutate(
    left_start = pmax(0, breakpoint_bed0 - window_size),
    left_end = breakpoint_bed0,
    right_start = breakpoint_bed0,
    right_end = breakpoint_bed0 + window_size
  )

left_bed <- regions %>%
  select(chromosome, left_start, left_end)

right_bed <- regions %>%
  select(chromosome, right_start, right_end)

regions_map <- regions %>%
  select(
    TE_ID,
    chromosome,
    insertion_position,
    breakpoint_bed0,
    left_start,
    left_end,
    right_start,
    right_end
  )

dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

left_path <- file.path(output_dir, "left.bed")
right_path <- file.path(output_dir, "right.bed")
map_path <- file.path(output_dir, "flanking_regions_map.tsv")

write.table(
  left_bed,
  file = left_path,
  sep = "\t",
  row.names = FALSE,
  col.names = FALSE,
  quote = FALSE
)

write.table(
  right_bed,
  file = right_path,
  sep = "\t",
  row.names = FALSE,
  col.names = FALSE,
  quote = FALSE
)

write.table(
  regions_map,
  file = map_path,
  sep = "\t",
  row.names = FALSE,
  col.names = TRUE,
  quote = FALSE
)

message("[INFO] Left BED: ", left_path)
message("[INFO] Right BED: ", right_path)
message("[INFO] Region map: ", map_path)
message("[INFO] Window size: ", window_size, " bp")
